# 🐼 Pandas – GroupBy
### Interview-focused Practice | Dataset: Employee Records

**Columns:** `employee_id`, `name`, `age`, `gender`, `department`, `city`, `salary`, `experience_years`, `rating`, `joining_year`, `is_manager`, `projects_completed`

**Methods you will practice:**
`df.groupby()` · `.mean()` · `.sum()` · `.count()` · `.min()` · `.max()` · `.agg()` · `.transform()` · `.apply()`

---
> ⚠️ All code cells are empty. Write your own answers!

---
## ⚙️ Setup – Run This First!

In [1]:
import pandas as pd
df = pd.read_csv('employees_dataset.csv')
print('✅ Dataset loaded!')
df.head()

✅ Dataset loaded!

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42

---
## 🟢 EASY (Q1–Q10)

### Q1. Find the average salary for each department.

In [3]:
df.groupby('department')['salary'].mean()

department
Engineering    100000.0
Finance        115000.0
HR              54250.0
Marketing       64600.0
Name: salary, dtype: float64

### Q2. Count the number of employees in each department.

In [7]:
df.groupby('department')['employee_id'].count()

department
Engineering    9
Finance        6
HR             5
Marketing      5
Name: employee_id, dtype: int64

### Q3. Find the total `projects_completed` for each department.

In [8]:
df.groupby('department')['projects_completed'].sum()

department
Engineering    251
Finance        210
HR              45
Marketing       68
Name: projects_completed, dtype: int64

### Q4. Find the maximum salary in each department.

In [9]:
df.groupby('department')['salary'].max()

department
Engineering    120000.0
Finance        155000.0
HR              58000.0
Marketing       75000.0
Name: salary, dtype: float64

### Q5. Find the minimum `experience_years` in each department.

In [10]:
df.groupby('department')['experience_years'].min()

department
Engineering    6
Finance        5
HR             1
Marketing      1
Name: experience_years, dtype: int64

### Q6. Find the average rating for each gender.

In [11]:
df.groupby('gender')['rating'].mean()

gender
Female    4.433333
Male      3.992308
Name: rating, dtype: float64

### Q7. Count the number of employees in each city.

In [13]:
df.groupby('city')['employee_id'].count()

city
Ahmedabad     2
Bangalore     4
Chandigarh    1
Chennai       1
Delhi         4
Hyderabad     1
Jaipur        1
Kochi         2
Kolkata       2
Lucknow       1
Mumbai        4
Pune          2
Name: employee_id, dtype: int64

### Q8. Find the total salary paid out per city.

In [14]:
df.groupby('city')['salary'].sum()

city
Ahmedabad     210000.0
Bangalore     437000.0
Chandigarh     84000.0
Chennai        88000.0
Delhi         241000.0
Hyderabad      53000.0
Jaipur         45000.0
Kochi         236000.0
Kolkata       190000.0
Lucknow        70000.0
Mumbai        220000.0
Pune          156000.0
Name: salary, dtype: float64

### Q9. Find the average `projects_completed` grouped by `is_manager`.

In [15]:
df.groupby('is_manager')['projects_completed'].mean()

is_manager
False    14.5
True     38.0
Name: projects_completed, dtype: float64

### Q10. Find the earliest `joining_year` for each department.

In [16]:
df.groupby('department')['joining_year'].min()

department
Engineering    2009
Finance        2003
HR             2015
Marketing      2014
Name: joining_year, dtype: int64

---
## 🟡 MEDIUM (Q11–Q20)

### Q11. Group by both `department` and `gender` and find the mean salary for each combination.

In [17]:
df.groupby(['department','gender'])['salary'].mean()

department   gender
Engineering  Female     97750.000000
             Male      102250.000000
Finance      Female     95000.000000
             Male      125000.000000
HR           Female     55333.333333
             Male       51000.000000
Marketing    Female     70000.000000
             Male       56500.000000
Name: salary, dtype: float64

### Q12. Group by `department` and find both the mean and max salary using `agg()`.

In [18]:
df.groupby('department')['salary'].agg(['mean','max'])

                 mean       max
department
Engineering  100000.0  120000.0
Finance      115000.0  155000.0
HR            54250.0   58000.0
Marketing     64600.0   75000.0

### Q13. Group by `department` and calculate the mean `salary`, mean `rating`, and total `projects_completed` all at once using `agg()`.

In [23]:
df.groupby('department').agg({
    'salary':'mean',
    'rating': 'mean',
    'projects_completed':'sum'
})

               salary    rating  projects_completed
department
Engineering  100000.0  4.288889                 251
Finance      115000.0  4.316667                 210
HR            54250.0  4.220000                  45
Marketing     64600.0  3.900000                  68

### Q14. Use `groupby` and `transform()` to add a new column `dept_avg_salary` that shows the average salary of each employee's department (same row count as original df).

In [26]:
df['dept_avg_salary'] = df.groupby('department')['salary'].transform('mean')
df

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,dept_avg_salary
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,100000.0
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,64600.0
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,100000.0
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,54250.0
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,115000.0
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,100000.0
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,64600.0
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,115000.0
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,54250.0
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,100000.0
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,64600.0
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,115000.0
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,100000.0
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,54250.0
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,115000.0
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,100000.0
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,64600.0
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,54250.0
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,100000.0
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,115000.0
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,64600.0
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,100000.0
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,54250.0
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,115000.0
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,100000.0

### Q15. Group by `department` and use `agg()` with named aggregations to produce columns called `avg_salary` and `total_projects`.

In [28]:
df.groupby('department').agg(
    avg_salary=('salary','mean'),
    total_project=('projects_completed','sum')
)

             avg_salary  total_project
department
Engineering    100000.0            251
Finance        115000.0            210
HR              54250.0             45
Marketing       64600.0             68

### Q16. Find the number of managers vs non-managers in each department using `groupby` on two columns.

In [30]:
df.groupby(['department', 'is_manager']).size()

department   is_manager
Engineering  False         4
             True          5
Finance      False         2
             True          4
HR           False         5
Marketing    False         5
dtype: int64

### Q17. Group by `department` and apply a custom function using `apply()` that returns the difference between the max and min salary in each group.

In [31]:
df.groupby('department')['salary'].apply(lambda x: x.max() - x.min())

department
Engineering    36000.0
Finance        85000.0
HR              7000.0
Marketing      30000.0
Name: salary, dtype: float64

### Q18. Group by `city` and find how many unique departments exist in each city.

In [37]:
df.groupby('city')['department'].nunique()

city
Ahmedabad     2
Bangalore     2
Chandigarh    1
Chennai       1
Delhi         2
Hyderabad     1
Jaipur        1
Kochi         2
Kolkata       2
Lucknow       1
Mumbai        3
Pune          2
Name: department, dtype: int64

### Q19. Group by `department` and sort the result by average salary descending.

In [39]:
df.groupby('department')['salary'].mean().sort_values(ascending=False)

department
Finance        115000.0
Engineering    100000.0
Marketing       64600.0
HR              54250.0
Name: salary, dtype: float64

### Q20. Group by `joining_year` and count how many employees joined each year. Sort by year ascending.

In [41]:
df.groupby('joining_year')['employee_id'].count().sort_index(ascending=True)

joining_year
2003    1
2005    1
2008    1
2009    1
2010    1
2012    1
2013    1
2014    1
2015    2
2016    2
2017    3
2018    2
2019    2
2020    2
2021    1
2022    1
2023    2
Name: employee_id, dtype: int64

---
## 🔴 HARD (Q21–Q30)
### Real interview questions — think carefully before coding

### Q21. ⭐ Interview Classic
What is the difference between `groupby` + `agg()` and `groupby` + `transform()`? Write a comment explaining the key difference in output shape, then demonstrate both.

In [ ]:
# agg():
# Returns one row per group (reduced output).

df.groupby('department')['salary'].agg('mean')

# transform():
# Returns the same number of rows as the original DataFrame.

df.groupby('department')['salary'].transform('mean')

### Q22. ⭐ Interview Classic
Add a column `salary_vs_dept_avg` that shows the difference between each employee's salary and their department's average salary. Use `transform()`.

In [47]:
df['avg_dept_salary'] = df.groupby('department')['salary'].transform('mean')
df['diff'] = df['salary'] - df['avg_dept_salary']

df

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,dept_avg_salary,avg_dept_salary,diff
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,100000.0,100000.0,-5000.0
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,64600.0,64600.0,7400.0
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,100000.0,100000.0,10000.0
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,54250.0,54250.0,750.0
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,115000.0,115000.0,15000.0
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,100000.0,100000.0,-12000.0
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,64600.0,64600.0,3400.0
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,115000.0,115000.0,-17000.0
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,54250.0,54250.0,-3250.0
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,100000.0,100000.0,15000.0
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,64600.0,64600.0,-19600.0
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,115000.0,115000.0,-23000.0
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,100000.0,100000.0,NaN
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,54250.0,54250.0,-1250.0
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,115000.0,115000.0,30000.0
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,100000.0,100000.0,-16000.0
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,64600.0,64600.0,10400.0
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,54250.0,54250.0,NaN
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,100000.0,100000.0,-9000.0
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,115000.0,115000.0,40000.0
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,64600.0,64600.0,-1600.0
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,100000.0,100000.0,20000.0
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,54250.0,54250.0,3750.0
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,115000.0,115000.0,-45000.0
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,100000.0,100000.0,-3000.0

### Q23. ⭐ Interview Classic
Find the top earner in each department. Use `groupby` and `apply()` only.

In [48]:
df.groupby('department').apply(lambda x: x.loc[x['salary'].idxmax()])

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,dept_avg_salary,avg_dept_salary,diff
department,,,,,,,,,,,,,,,
Engineering,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,100000.0,100000.0,20000.0
Finance,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,115000.0,115000.0,40000.0
HR,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,54250.0,54250.0,3750.0
Marketing,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,64600.0,64600.0,10400.0

### Q24. ⭐ Interview Classic
Group by `department` and compute a custom aggregation using `agg()` with a lambda that returns the range (max - min) of `experience_years` per department.

In [49]:
df.groupby('department').agg(
    experience_range=('experience_years',
                      lambda x: x.max() - x.min())
)

             experience_range
department
Engineering                 9
Finance                    16
HR                          8
Marketing                   9

### Q25. ⭐ Interview Classic
Find departments where the average salary is above the overall company average salary. Print only those department names.

In [50]:
company_avg = df['salary'].mean()

df.groupby('department')['salary'].mean().loc[lambda x: x > company_avg].index

Index(['Engineering', 'Finance'], dtype='object', name='department')

### Q26. ⭐ Interview Classic
Add a column `salary_rank_in_dept` that ranks each employee by salary within their department (rank 1 = highest). Use `groupby` and `rank()`.

In [55]:
df['salary_rank_in_dept'] = df.groupby('department')['salary'].rank(method='dense',ascending=False)
df

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,dept_avg_salary,avg_dept_salary,diff,salary_rank_in_dept
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,100000.0,100000.0,-5000.0,5.0
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,64600.0,64600.0,7400.0,2.0
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,100000.0,100000.0,10000.0,3.0
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,54250.0,54250.0,750.0,2.0
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,115000.0,115000.0,15000.0,3.0
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,100000.0,100000.0,-12000.0,7.0
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,64600.0,64600.0,3400.0,3.0
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,115000.0,115000.0,-17000.0,4.0
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,54250.0,54250.0,-3250.0,4.0
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,100000.0,100000.0,15000.0,2.0
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,64600.0,64600.0,-19600.0,5.0
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,115000.0,115000.0,-23000.0,5.0
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,100000.0,100000.0,NaN,NaN
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,54250.0,54250.0,-1250.0,3.0
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,115000.0,115000.0,30000.0,2.0
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,100000.0,100000.0,-16000.0,8.0
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,64600.0,64600.0,10400.0,1.0
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,54250.0,54250.0,NaN,NaN
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,100000.0,100000.0,-9000.0,6.0
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,115000.0,115000.0,40000.0,1.0
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,64600.0,64600.0,-1600.0,4.0
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,100000.0,100000.0,20000.0,1.0
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,54250.0,54250.0,3750.0,1.0
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,115000.0,115000.0,-45000.0,6.0
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,100000.0,100000.0,-3000.0,4.0

### Q27. ⭐ Interview Classic
Group by `department` and use `agg()` to find — for each department — the mean salary, the count of employees, and the max rating, all in one call with custom column names.

In [56]:
df.groupby('department').agg(
    avg_salary =('salary','mean'),
    employee_count = ('employee_id','sum'),
    max_rating= ('rating','max')
)

             avg_salary  employee_count  max_rating
department
Engineering    100000.0            1015         4.8
Finance        115000.0             684         4.7
HR              54250.0             568         4.7
Marketing       64600.0             558         4.2

### Q28. ⭐ Interview Classic
For each department, find the employee with the most `projects_completed`. Return a DataFrame with department and that employee's name and project count.

In [57]:
df.groupby('department').apply(
    lambda x: x.loc[x['projects_completed'].idxmax(),
                    ['name', 'projects_completed']]
)

                       name  projects_completed
department
Engineering     Deepak Jain                  40
Finance         Tarun Bhatt                  55
HR           Swati Kulkarni                  18
Marketing         Riya Bose                  21

### Q29. ⭐ Interview Classic
Use `groupby` and `filter()` to keep only the rows belonging to departments that have more than 4 employees.

In [58]:
df.groupby('department').filter(lambda x: len(x) > 4)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,dept_avg_salary,avg_dept_salary,diff,salary_rank_in_dept
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,100000.0,100000.0,-5000.0,5.0
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,64600.0,64600.0,7400.0,2.0
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,100000.0,100000.0,10000.0,3.0
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,54250.0,54250.0,750.0,2.0
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,115000.0,115000.0,15000.0,3.0
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,100000.0,100000.0,-12000.0,7.0
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,64600.0,64600.0,3400.0,3.0
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,115000.0,115000.0,-17000.0,4.0
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,54250.0,54250.0,-3250.0,4.0
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,100000.0,100000.0,15000.0,2.0
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,64600.0,64600.0,-19600.0,5.0
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,115000.0,115000.0,-23000.0,5.0
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,100000.0,100000.0,NaN,NaN
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,54250.0,54250.0,-1250.0,3.0
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,115000.0,115000.0,30000.0,2.0
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,100000.0,100000.0,-16000.0,8.0
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,64600.0,64600.0,10400.0,1.0
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,54250.0,54250.0,NaN,NaN
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,100000.0,100000.0,-9000.0,6.0
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,115000.0,115000.0,40000.0,1.0
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,64600.0,64600.0,-1600.0,4.0
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,100000.0,100000.0,20000.0,1.0
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,54250.0,54250.0,3750.0,1.0
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,115000.0,115000.0,-45000.0,6.0
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,100000.0,100000.0,-3000.0,4.0

### Q30. ⭐ Interview Classic
Group by `department` and `gender`. For each group find the mean salary. Then unstack the result so that gender becomes columns. This is a very common interview output format.

In [61]:
df.groupby(['department', 'gender'])['salary'].mean().unstack()

gender             Female      Male
department
Engineering  97750.000000  102250.0
Finance      95000.000000  125000.0
HR           55333.333333   51000.0
Marketing    70000.000000   56500.0

---
## ✅ Done with GroupBy!

| Method | Practiced in |
|--------|--------------|
| `groupby().mean()` | Q1, Q6, Q9, Q11 |
| `groupby().sum()` | Q3, Q8 |
| `groupby().count()` | Q2, Q7, Q16, Q20 |
| `groupby().min()` / `.max()` | Q4, Q5, Q10 |
| `groupby().agg()` | Q12, Q13, Q15, Q24, Q27 |
| `groupby().transform()` | Q14, Q21, Q22 |
| `groupby().apply()` | Q17, Q23 |
| `groupby().filter()` | Q29 |
| `groupby().rank()` | Q26 |
| `unstack()` | Q30 |

**Next up → Merging & Joining 🚀**