# 🐼 Pandas – Filtering Data
### Interview-focused Practice | Dataset: Employee Records

**Columns:** `employee_id`, `name`, `age`, `gender`, `department`, `city`, `salary`, `experience_years`, `rating`, `joining_year`, `is_manager`, `projects_completed`

**Methods you will practice:**
`df[condition]` · `&` `|` operators · `df.isnull()` · `df.notnull()` · `df.dropna()` · `df.fillna()` · `df.duplicated()` · `df.drop_duplicates()`

---
> ⚠️ All code cells are empty. Write your own answers!

---
## ⚙️ Setup – Run This First!

In [1]:
import pandas as pd
df = pd.read_csv('employees_dataset.csv')
print('✅ Dataset loaded!')
df.head()

✅ Dataset loaded!

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42

---
## 🟢 EASY (Q1–Q10)

### Q1. Filter all employees whose salary is greater than 90000.

In [4]:
df[df['salary']>90000]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q2. Filter all employees who work in the `Engineering` department.

In [6]:
df[df['department']== 'Engineering']

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q3. Filter all female employees.

In [7]:
df[df['gender']== 'Female']

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q4. Check which cells in the entire DataFrame are null using `isnull()`.

In [15]:
df.isnull()

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,True,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False

<!-- ### Q5. Check which cells are NOT null using `notnull()`. -->

### Q5. Check which cells are NOT null using notnull().

In [16]:
df.notnull()

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,False,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,False,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True,True

### Q6. Drop all rows that have any missing values using `dropna()`.

In [17]:
df.dropna()

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q7. Fill all missing values in the dataset with `0` using `fillna()`.

In [20]:
df.fillna(0)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,0.0,14,4.0,2010,True,35
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
17,118,Siddharth Roy,22,Male,HR,Mumbai,0.0,1,3.4,2023,False,3
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q8. Check if there are any duplicate rows in the dataset using `duplicated()`.

In [25]:
df.duplicated().sum()

0

### Q9. Filter all employees who are managers (`is_manager == True`).

In [34]:
# df[df['is_manager'] == True]
df[df['is_manager']]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40

### Q10. Filter employees who joined in the year 2017.

In [28]:
df[df['joining_year']==2017]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

---
## 🟡 MEDIUM (Q11–Q20)

### Q11. Filter employees in `Engineering` department AND with a rating above 4.0 (multiple conditions).

In [33]:
df[(df['department']=='Engineering') & (df['rating']>4.0)]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q12. Filter employees who are either in `HR` OR have less than 3 years of experience.

In [38]:
df[(df['department']=='HR') | (df['experience_years']<3)]
df.query("department == 'HR' or experience_years <3")

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18

### Q13. Find the total number of missing values in each column.

In [39]:
df.isnull().sum()

employee_id           0
name                  0
age                   0
gender                0
department            0
city                  0
salary                2
experience_years      0
rating                0
joining_year          0
is_manager            0
projects_completed    0
dtype: int64

### Q14. Fill missing values in the `salary` column specifically with the value `50000`. Leave other columns unchanged.

In [41]:
df['salary']=df['salary'].fillna(50000)

### Q15. Drop rows where the `salary` column specifically is missing.

In [42]:
df.dropna(subset=['salary'])

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,50000.0,14,4.0,2010,True,35
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
17,118,Siddharth Roy,22,Male,HR,Mumbai,50000.0,1,3.4,2023,False,3
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q16. Filter employees whose salary is between 70000 and 120000 (inclusive).

In [47]:
df[(df['salary']<=120000) & (df['salary']>=70000)]
df[df['salary'].between(70000,120000)]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q17. Filter employees whose department is NOT `Marketing`.

In [51]:
df[df['department'] != 'marketing']
df.query("department != 'marketing'")

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,50000.0,14,4.0,2010,True,35
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
17,118,Siddharth Roy,22,Male,HR,Mumbai,50000.0,1,3.4,2023,False,3
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q18. Add a duplicate row manually to the DataFrame, then use `drop_duplicates()` to remove it and confirm the shape before and after.

In [52]:
# Add a duplicate of the first row
df_dup = pd.concat([df, df.iloc[[0]]], ignore_index=True)

# Shape before removing duplicates
print("Before:", df_dup.shape)

# Remove duplicate rows
df_dup = df_dup.drop_duplicates()

# Shape after removing duplicates
print("After:", df_dup.shape)

Before: (26, 12)
After: (25, 12)

### Q19. Filter all rows where `salary` is null using `isnull()`.

In [55]:
df[df['salary'].isnull()]

Empty DataFrame
Columns: [employee_id, name, age, gender, department, city, salary, experience_years, rating, joining_year, is_manager, projects_completed]
Index: []

### Q20. Filter employees from `Bangalore` or `Mumbai` who have completed more than 20 projects.

In [64]:
df[(df['city'].isin(['Bangalore','Mumbai'])) & (df['projects_completed']>20)]
# OR
df.query("city in ['Bangalore','Mumbai'] and projects_completed>20")

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

---
## 🔴 HARD (Q21–Q30)
### Real interview questions — think carefully before coding

### Q21. ⭐ Interview Classic
What is the difference between `dropna()` and `fillna()`? Write a comment, then show a case where dropping is better vs filling is better using this dataset.

In [ ]:
# Difference:
# dropna() removes rows or columns containing missing (NaN) values.
# fillna() replaces missing (NaN) values with a specified value, keeping the data.

# Example where dropping is better:
# Remove employees whose salary is missing.
df.dropna(subset=['salary'])

# Example where filling is better:
# Replace missing salaries with 50000 instead of removing those employees.
df['salary'].fillna(50000)

### Q22. ⭐ Interview Classic
Fill missing `salary` values with the **mean salary** of the entire column (not a hardcoded number).

In [68]:
# df.describe().loc['mean','salary']
df['salary'].fillna(df.describe().loc['mean','salary'])


df['salary'].fillna(df['salary'].mean())

0      95000.0
1      72000.0
2     110000.0
3      55000.0
4     130000.0
5      88000.0
6      68000.0
7      98000.0
8      51000.0
9     115000.0
10     45000.0
11     92000.0
12     50000.0
13     53000.0
14    145000.0
15     84000.0
16     75000.0
17     50000.0
18     91000.0
19    155000.0
20     63000.0
21    120000.0
22     58000.0
23     70000.0
24     97000.0
Name: salary, dtype: float64

### Q23. ⭐ Interview Classic
Filter employees whose `name` contains the letter `a` (case-insensitive). Do not loop — use a pandas string method.

In [69]:
df[df['name'].str.contains('a', case=False, na=False)]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,50000.0,14,4.0,2010,True,35
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
17,118,Siddharth Roy,22,Male,HR,Mumbai,50000.0,1,3.4,2023,False,3
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q24. ⭐ Interview Classic
`dropna()` has a `thresh` parameter. Use it to keep only rows that have at least 11 non-null values.

In [70]:
df.dropna(thresh=11)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,50000.0,14,4.0,2010,True,35
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
17,118,Siddharth Roy,22,Male,HR,Mumbai,50000.0,1,3.4,2023,False,3
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q25. ⭐ Interview Classic
What does `duplicated(keep='last')` do differently from `duplicated(keep='first')`? Demonstrate with an example.

In [ ]:
# keep='first' (default):
# Marks duplicate rows as True except for the first occurrence.

# keep='last':
# Marks duplicate rows as True except for the last occurrence.

# Example
df_dup = pd.concat([df, df.iloc[[0]]], ignore_index=True)

print(df_dup.duplicated(keep='first'))
print(df_dup.duplicated(keep='last'))

### Q26. Find employees who have BOTH a missing salary AND less than 2 years of experience.

In [74]:
df[df['salary'].isnull() & (df['experience_years'] < 2)]

# or
df.query("salary.isnull() and experience < 2")

Empty DataFrame
Columns: [employee_id, name, age, gender, department, city, salary, experience_years, rating, joining_year, is_manager, projects_completed]
Index: []

### Q27. ⭐ Interview Classic
Filter employees where `experience_years` is between 5 and 10 using `.between()` — not with `&` operators.

In [75]:
df[df['experience_years'].between(5, 10)]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q28. ⭐ Interview Classic
Use `isnull().sum()` to print a clean report showing only columns that have at least 1 missing value and how many.

In [77]:
df.isnull().sum()>0

employee_id           False
name                  False
age                   False
gender                False
department            False
city                  False
salary                False
experience_years      False
rating                False
joining_year          False
is_manager            False
projects_completed    False
dtype: bool

### Q29. ⭐ Interview Classic
Without hardcoding department names, filter all employees who belong to departments that have more than 4 employees. (Think: you need to count per department first.)

In [86]:
dept_counts = df['department'].value_counts()
df[df['department'].isin(dept_counts[dept_counts > 4].index)]

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,50000.0,14,4.0,2010,True,35
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
17,118,Siddharth Roy,22,Male,HR,Mumbai,50000.0,1,3.4,2023,False,3
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q30. ⭐ Interview Classic
A common interview scenario: the dataset has missing salaries. Fill them using the **median salary of the employee's own department** (not the overall median). Each department should get its own median.

In [87]:
df['salary'] = df['salary'].fillna(
    df.groupby('department')['salary'].transform('median')
)

---
## ✅ Done with Filtering Data!

| Method | Practiced in |
|--------|--------------|
| `df[condition]` | Q1, Q2, Q3, Q9, Q10, Q17 |
| Multiple conditions `&` `\|` | Q11, Q12, Q16, Q20, Q26 |
| `df.isnull()` | Q4, Q13, Q19, Q28 |
| `df.notnull()` | Q5 |
| `df.dropna()` | Q6, Q15, Q21, Q24 |
| `df.fillna()` | Q7, Q14, Q21, Q22, Q30 |
| `df.duplicated()` | Q8, Q25 |
| `df.drop_duplicates()` | Q18 |
| `.str.contains()` | Q23 |
| `.between()` | Q27 |

**Next up → Sorting & Ordering 🚀**