# 🐼 Pandas Basics – Extra Practice (Set 2)
### Dataset: Student Marks & Attendance
All code cells are empty. Fill in your answers yourself!

---
## ⚙️ Setup – Run This First!

In [1]:
import pandas as pd 
df = pd.read_csv("students_dataset.csv")
print('✅ Dataset loaded!')

✅ Dataset loaded!

---
## 🟢 EASY (Q1–Q10)

### Q1. Display the first 10 rows of the dataset.

In [3]:
df.head(10)

,student_id,name,age,gender,city,math_score,science_score,english_score,attendance_percent,passed,grade
0,1,Aarav Sharma,16,Male,Mumbai,88.0,92,78.0,95,True,A
1,2,Priya Nair,17,Female,Chennai,72.0,68,85.0,88,True,B
2,3,Rohan Mehta,15,Male,Delhi,55.0,60,50.0,70,False,D
3,4,Sneha Patel,16,Female,Ahmedabad,91.0,95,89.0,98,True,A
4,5,Kiran Rao,17,Male,Bangalore,63.0,58,72.0,80,True,C
5,6,Divya Iyer,15,Female,Chennai,78.0,82,80.0,92,True,B
6,7,Aditya Kumar,18,Male,Delhi,45.0,50,40.0,60,False,F
7,8,Meera Joshi,16,Female,Pune,84.0,79,88.0,94,True,A
8,9,Vivek Singh,17,Male,Mumbai,67.0,71,65.0,75,True,C
9,10,Ananya Das,15,Female,Kolkata,90.0,88,92.0,99,True,A

### Q2. Display the last 5 rows of the dataset.

In [4]:
df.tail(5)

,student_id,name,age,gender,city,math_score,science_score,english_score,attendance_percent,passed,grade
15,16,Ishaan Chopra,16,Male,Chandigarh,70.0,65,73.0,85,True,C
16,17,Riya Bose,17,Female,Kolkata,88.0,91,86.0,96,True,A
17,18,Siddharth Roy,15,Male,Mumbai,42.0,45,NaN,55,False,F
18,19,Kavya Menon,16,Female,Kochi,79.0,83,77.0,90,True,B
19,20,Tarun Bhatt,18,Male,Ahmedabad,65.0,60,70.0,78,True,C

### Q3. Print the total number of rows in the dataset.

In [5]:
df.shape[0]

20

### Q4. Print the total number of columns in the dataset.

In [10]:
# len(df.columns)
df.shape[1]

11

In [11]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'city', 'math_score',
       'science_score', 'english_score', 'attendance_percent', 'passed',
       'grade'],
      dtype='object')

### Q5. Print the data type of each column.

In [12]:
df.dtypes

student_id              int64
name                   object
age                     int64
gender                 object
city                   object
math_score            float64
science_score           int64
english_score         float64
attendance_percent      int64
passed                   bool
grade                  object
dtype: object

### Q6. Print only the index of the DataFrame.

In [13]:
df.index

RangeIndex(start=0, stop=20, step=1)

### Q7. Create a Series of 5 cities: `['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Pune']` and print it.

In [15]:
s= pd.Series(['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Pune'])
print(s)

0       Mumbai
1        Delhi
2    Bangalore
3      Chennai
4         Pune
dtype: object

### Q8. Create a DataFrame with 2 columns `subject` and `max_marks` for 4 subjects of your choice.

In [18]:
dt={'subject':['math','eng'],'marks':[10,20]}
scores=  pd.DataFrame(dt)
scores

  subject  marks
0    math     10
1     eng     20

In [27]:
subject=['math','eng','hindi']
marks = [10,20,30]
score= pd.DataFrame({'subject':subject,'marks':marks})
score

  subject  marks
0    math     10
1     eng     20
2   hindi     30

### Q9. Check how many non-null values are in each column.

In [20]:
df.count()

student_id            20
name                  20
age                   20
gender                20
city                  20
math_score            19
science_score         20
english_score         19
attendance_percent    20
passed                20
grade                 20
dtype: int64

In [23]:
df.isnull().sum()

student_id            0
name                  0
age                   0
gender                0
city                  0
math_score            1
science_score         0
english_score         1
attendance_percent    0
passed                0
grade                 0
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          20 non-null     int64
 1   name                20 non-null     object
 2   age                 20 non-null     int64
 3   gender              20 non-null     object
 4   city                20 non-null     object
 5   math_score          19 non-null     float64
 6   science_score       20 non-null     int64
 7   english_score       19 non-null     float64
 8   attendance_percent  20 non-null     int64
 9   passed              20 non-null     bool
 10  grade               20 non-null     object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 1.7+ KB

### Q10. Print just the column names as a plain Python list (not an Index object).

In [43]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'city',
 'math_score',
 'science_score',
 'english_score',
 'attendance_percent',
 'passed',
 'grade']

---
## 🟡 MEDIUM (Q11–Q20)

### Q11. Print the minimum value of the `science_score` column using `df.describe()`.

In [27]:
df.describe()

,student_id,age,math_score,science_score,english_score,attendance_percent
count,20.00000,20.000000,19.000000,20.000000,19.000000,20.000000
mean,10.50000,16.400000,70.894737,71.800000,72.631579,82.700000
std,5.91608,1.095445,15.249389,15.463369,14.150817,13.006476
min,1.00000,15.000000,42.000000,45.000000,40.000000,55.000000
25%,5.75000,15.750000,61.000000,60.000000,66.500000,74.250000
50%,10.50000,16.000000,72.000000,71.500000,74.000000,86.000000
75%,15.25000,17.000000,83.500000,84.000000,83.000000,93.250000
max,20.00000,18.000000,91.000000,95.000000,92.000000,99.000000

In [52]:
df.describe().loc['min','science_score']

45.0

### Q12. Print the 25th percentile of `attendance_percent` using `df.describe()`.

In [56]:
df.describe().loc['25%','attendance_percent']

74.25

### Q13. How many columns have missing values? Print the count.

In [62]:
(df.isnull().sum()>0).sum()

2

In [35]:
(df.isnull().sum()>0).sum()

2

### Q14. Create a DataFrame using a list of dictionaries for 4 students with columns: `name`, `math_score`, `english_score`.

In [65]:
import pandas as pd

students = [
    {'name': 'Alice', 'math_score': 85, 'english_score': 78},
    {'name': 'Bob', 'math_score': 92, 'english_score': 88},
    {'name': 'Charlie', 'math_score': 76, 'english_score': 81},
    {'name': 'David', 'math_score': 89, 'english_score': 90}
]

scores= pd.DataFrame(students)
scores

      name  math_score  english_score
0    Alice          85             78
1      Bob          92             88
2  Charlie          76             81
3    David          89             90

### Q15. Print the shape of the DataFrame you created in Q14.

In [36]:
scores.shape

(2, 2)

### Q16. Create a Series of 6 science scores with student names as the index. Then print the length of the Series.

In [73]:
names =['a','b','c','d','e','f']
mark=[10,20,30,40,50,60]
stud_marks = pd.Series(mark,index=names,name='science_Scores')
stud_marks

a    10
b    20
c    30
d    40
e    50
f    60
Name: science_Scores, dtype: int64

In [74]:
len(stud_marks)

6

### Q17. Using `df.describe()`, print a sentence: `"The average English score is X"` where X is the actual value from describe.

In [80]:
avg_eng_score = df.describe().loc['mean','english_score']
print(f"he average English score is {avg_eng_score}")

he average English score is 72.63157894736842

### Q18. Set the `name` column as the index of the DataFrame and display the first 5 rows.

In [39]:
# df.set_index("name",inplace=True)
df.head()

,student_id,age,gender,city,math_score,science_score,english_score,attendance_percent,passed,grade
name,,,,,,,,,,
Aarav Sharma,1,16,Male,Mumbai,88.0,92,78.0,95,True,A
Priya Nair,2,17,Female,Chennai,72.0,68,85.0,88,True,B
Rohan Mehta,3,15,Male,Delhi,55.0,60,50.0,70,False,D
Sneha Patel,4,16,Female,Ahmedabad,91.0,95,89.0,98,True,A
Kiran Rao,5,17,Male,Bangalore,63.0,58,72.0,80,True,C

### Q19. After setting `name` as index (Q18), reset the index back to the default numeric index and display the first 5 rows.

In [41]:
df.reset_index(inplace=True)
df.head(5)

,index,name,student_id,age,gender,city,math_score,science_score,english_score,attendance_percent,passed,grade
0,0,Aarav Sharma,1,16,Male,Mumbai,88.0,92,78.0,95,True,A
1,1,Priya Nair,2,17,Female,Chennai,72.0,68,85.0,88,True,B
2,2,Rohan Mehta,3,15,Male,Delhi,55.0,60,50.0,70,False,D
3,3,Sneha Patel,4,16,Female,Ahmedabad,91.0,95,89.0,98,True,A
4,4,Kiran Rao,5,17,Male,Bangalore,63.0,58,72.0,80,True,C

### Q20. Print the memory usage of the DataFrame using `df.info(memory_usage=True)`.

In [102]:
df.info().memory_

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                20 non-null     object
 1   student_id          20 non-null     int64
 2   age                 20 non-null     int64
 3   gender              20 non-null     object
 4   city                20 non-null     object
 5   math_score          19 non-null     float64
 6   science_score       20 non-null     int64
 7   english_score       19 non-null     float64
 8   attendance_percent  20 non-null     int64
 9   passed              20 non-null     bool
 10  grade               20 non-null     object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 1.7+ KB

---
## 🔴 HARD (Q21–Q30)

### Q21. Print a full summary: total rows, total columns, column names, data types, and whether any nulls exist — all in one clean output block.

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                20 non-null     object
 1   student_id          20 non-null     int64
 2   age                 20 non-null     int64
 3   gender              20 non-null     object
 4   city                20 non-null     object
 5   math_score          19 non-null     float64
 6   science_score       20 non-null     int64
 7   english_score       19 non-null     float64
 8   attendance_percent  20 non-null     int64
 9   passed              20 non-null     bool
 10  grade               20 non-null     object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 1.7+ KB

In [104]:
print(f"""
DataFrame Summary
-----------------
Total Rows    : {df.shape[0]}
Total Columns : {df.shape[1]}

Column Names  : {df.columns.tolist()}

Data Types:
{df.dtypes}

Any Nulls?    : {df.isnull().values.any()}
""")

DataFrame Summary
-----------------
Total Rows    : 20
Total Columns : 11

Column Names  : ['name', 'student_id', 'age', 'gender', 'city', 'math_score', 'science_score', 'english_score', 'attendance_percent', 'passed', 'grade']

Data Types:
name                   object
student_id              int64
age                     int64
gender                 object
city                   object
math_score            float64
science_score           int64
english_score         float64
attendance_percent      int64
passed                   bool
grade                  object
dtype: object

Any Nulls?    : True

### Q22. Create a DataFrame from scratch that has 5 rows and 4 columns of your choice. Then verify its shape using `df.shape` and column names using `df.columns`.

In [43]:
name = ["abd","cdm","fsd","dse","sdr"]
age =[1,2,3,4,5]
gender=['M','M','M','M','M']
salary = [1,1,1,1,1]

cust_info = pd.DataFrame({
    "name":name,
    "age":age,
    "gender":gender,
    "salary":salary})
cust_info
cust_info.shape
cust_info.columns.tolist()

['name', 'age', 'gender', 'salary']

### Q23. Using `df.describe(include='all')`, find which city appears most often in the dataset and how many times.

In [44]:
cust_info.describe(include='all')

       name       age gender  salary
count     5  5.000000      5     5.0
unique    5       NaN      1     NaN
top     abd       NaN      M     NaN
freq      1       NaN      5     NaN
mean    NaN  3.000000    NaN     1.0
std     NaN  1.581139    NaN     0.0
min     NaN  1.000000    NaN     1.0
25%     NaN  2.000000    NaN     1.0
50%     NaN  3.000000    NaN     1.0
75%     NaN  4.000000    NaN     1.0
max     NaN  5.000000    NaN     1.0

### Q24. Print the difference between the max and min `math_score` using only `df.describe()`.

In [45]:
# df.describe()
df.describe().loc["max","math_score"] - df.describe().loc["min","math_score"]

49.0

### Q25. Create a Series of 10 random integers (use Python's built-in `range` or a list) and give it a custom string index. Then print its length and index.

In [47]:

import random
s = pd.Series(
    [random.randint(1, 100) for _ in range(10)],
    index=["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
)

print("Series:")
print(s)

# Print length
print("\nLength:", len(s))

# Print index
print("\nIndex:")
print(s.index)

Series:
A     4
B    90
C    25
D    64
E     6
F     9
G    63
H    61
I    95
J    54
dtype: int64

Length: 10

Index:
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object')

### Q26. Load the CSV again but this time set `student_id` as the index directly while reading the file (in the `pd.read_csv()` call itself).

In [51]:
df= pd.read_csv('students_dataset.csv',index_col='student_id')
df.head(5)

,name,age,gender,city,math_score,science_score,english_score,attendance_percent,passed,grade
student_id,,,,,,,,,,
1,Aarav Sharma,16,Male,Mumbai,88.0,92,78.0,95,True,A
2,Priya Nair,17,Female,Chennai,72.0,68,85.0,88,True,B
3,Rohan Mehta,15,Male,Delhi,55.0,60,50.0,70,False,D
4,Sneha Patel,16,Female,Ahmedabad,91.0,95,89.0,98,True,A
5,Kiran Rao,17,Male,Bangalore,63.0,58,72.0,80,True,C

### Q27. Using only `df.shape` and `df.describe()`, print: how many numeric columns have a standard deviation greater than 10.

In [57]:
(df.describe().loc['std']>10).sum()

4

### Q28. Check if the DataFrame has any duplicate rows using a method from `df`. Print `True` or `False`.

In [63]:
df.duplicated().sum()
df.duplicated().any()

False

### Q29. Reload the CSV with only the first 10 rows (using a parameter inside `pd.read_csv()`). Verify using `df.shape`.

In [69]:
df= pd.read_csv("students_dataset.csv",nrows=10)
df.shape[0]

20

### Q30. Using `df.describe()`, find which numeric column has the highest average score among `math_score`, `science_score`, and `english_score`. Print the column name and its mean.

In [85]:
mean_scores = df.describe().loc['mean',['math_score', 'science_score', 'english_score']]
print(mean_scores.idxmax())
print(mean_scores.max())

english_score
72.63157894736842

In [86]:
df.describe().loc['mean',['math_score', 'science_score', 'english_score']].idxmax()
df.describe().loc['mean',['math_score', 'science_score', 'english_score']].max()

72.63157894736842

---
## ✅ Done with Set 1!
**Part 2 → Selecting Data 🚀**