# 🐼 Pandas – Sorting & Ordering
### Interview-focused Practice | Dataset: Employee Records

**Columns:** `employee_id`, `name`, `age`, `gender`, `department`, `city`, `salary`, `experience_years`, `rating`, `joining_year`, `is_manager`, `projects_completed`

**Methods you will practice:**
`df.sort_values()` · `df.sort_index()` · `df.nlargest()` · `df.nsmallest()`

---
> ⚠️ All code cells are empty. Write your own answers!

---
## ⚙️ Setup – Run This First!

In [1]:
import pandas as pd
df = pd.read_csv('employees_dataset.csv')
print('✅ Dataset loaded!')
df.head()

✅ Dataset loaded!

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42

---
## 🟢 EASY (Q1–Q10)

### Q1. Sort the DataFrame by `salary` in ascending order.

In [3]:
df.sort_values(by='salary')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3

### Q2. Sort the DataFrame by `salary` in descending order.

In [4]:
df.sort_values(by='salary',ascending=False)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3

### Q3. Sort the DataFrame by `name` alphabetically (A to Z).

In [5]:
df.sort_values(by='name')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10

### Q4. Sort the DataFrame by `rating` from highest to lowest.

In [6]:
df.sort_values(by='rating',ascending =False)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3

### Q5. Get the top 5 highest paid employees using `nlargest()`.

In [7]:
df.nlargest(5,'salary')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38

### Q6. Get the 5 employees with the least experience using `nsmallest()`.

In [8]:
df.nsmallest(5,'experience_years')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10

### Q7. Sort the DataFrame by its index in descending order using `sort_index()`.

In [9]:
df.sort_index(ascending=False)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23

### Q8. Sort by `experience_years` in ascending order and reset the index in the result.

In [10]:
df.sort_values(by='experience_years').reset_index()

,index,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
0,17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
1,10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
2,13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
3,3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
4,20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
5,8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
6,1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
7,23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
8,5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
9,15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
10,24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
11,7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
12,11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
13,18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
14,0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
15,6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
16,22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
17,16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
18,2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
19,9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
20,12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
21,21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
22,4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
23,14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
24,19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55

### Q9. Get the 3 employees with the most projects completed using `nlargest()`.

In [13]:
df.nlargest(3,'projects_completed')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42

### Q10. Sort the DataFrame by `joining_year` from oldest to newest.

In [14]:
df.sort_values(by='joining_year')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3

---
## 🟡 MEDIUM (Q11–Q20)

### Q11. Sort by `department` (A to Z) and within each department sort by `salary` (highest first) — multi-column sort.

In [15]:
df.sort_values(by=['department','salary'],ascending=[True,False])

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4

### Q12. Sort by `rating` descending and `experience_years` descending at the same time.

In [16]:
df.sort_values(by=['rating','experience_years'],ascending=[False,False])

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3

### Q13. Sort by `department` ascending and `salary` descending at the same time. Notice how `ascending` accepts a list.

In [18]:
df.sort_values(by=['department','salary'],ascending=[True,False])

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4

### Q14. Sort by `salary` descending and display only the `name`, `department`, and `salary` columns.

In [21]:
df.sort_values(by ='salary',ascending=False)[['name','department','salary']]

              name   department    salary
19     Tarun Bhatt      Finance  155000.0
14   Arjun Nambiar      Finance  145000.0
4        Kiran Rao      Finance  130000.0
21     Deepak Jain  Engineering  120000.0
9       Ananya Das  Engineering  115000.0
2      Rohan Mehta  Engineering  110000.0
7      Meera Joshi      Finance   98000.0
24    Aditi Sharma  Engineering   97000.0
0     Arjun Sharma  Engineering   95000.0
11  Lakshmi Pillai      Finance   92000.0
18     Kavya Menon  Engineering   91000.0
5       Divya Iyer  Engineering   88000.0
15   Ishaan Chopra  Engineering   84000.0
16       Riya Bose    Marketing   75000.0
1       Priya Nair    Marketing   72000.0
23   Manish Tiwari      Finance   70000.0
6     Aditya Kumar    Marketing   68000.0
20   Nisha Agarwal    Marketing   63000.0
22  Swati Kulkarni           HR   58000.0
3      Sneha Patel           HR   55000.0
13     Pooja Reddy           HR   53000.0
8      Vivek Singh           HR   51000.0
10     Rahul Verma    Marketing   45000.0
12    Nikhil Gupta  Engineering       NaN
17   Siddharth Roy           HR       NaN

### Q15. Set `employee_id` as the index, then sort the index in ascending order.

In [22]:
df.set_index('employee_id').sort_index()

,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
employee_id,,,,,,,,,,,
101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q16. Use `nlargest()` to get the top 5 employees by `salary` but only return their `name` and `salary`.

In [25]:
df.nlargest(5,'salary')[['name','salary']]

             name    salary
19    Tarun Bhatt  155000.0
14  Arjun Nambiar  145000.0
4       Kiran Rao  130000.0
21    Deepak Jain  120000.0
9      Ananya Das  115000.0

### Q17. Sort by `salary` and keep NaN values at the top instead of the bottom.

In [27]:
df.sort_values(by='salary',na_position='first')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55

### Q18. Sort the DataFrame by `rating` descending, then get only the top 10 rows from that sorted result.

In [29]:
df.sort_values(by='rating',ascending= False).head(10)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24

### Q19. Get the bottom 3 rated employees using `nsmallest()` on the `rating` column.

In [31]:
df.nsmallest(3,'rating')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4

### Q20. Sort by `joining_year` ascending. Among employees who joined the same year, sort by `name` alphabetically.

In [34]:
df.sort_values(by=['joining_year','name'],ascending=[True,True])
# OR
df.sort_values(by=['joining_year','name'])

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3

---
## 🔴 HARD (Q21–Q30)
### Real interview questions — think carefully before coding

### Q21. ⭐ Interview Classic
What is the difference between `sort_values()` and `nlargest()`? When would you prefer one over the other? Write a comment then demonstrate both to get the top 5 salaries.

In [ ]:
# sort_values():
# Sorts the entire DataFrame.

# nlargest():
# Efficiently returns only the top N rows based on a column without sorting the entire DataFrame.

# Using sort_values()
df.sort_values('salary', ascending=False).head(5)

# Using nlargest()
df.nlargest(5, 'salary')

### Q22. ⭐ Interview Classic
Sort the DataFrame by `salary` descending using `sort_values()` with `inplace=True`. What does `inplace=True` mean? Write a comment explaining it.

In [37]:
# inplace=True means:
# It modifies the original DataFrame directly and returns None.

df.sort_values('salary', ascending=False, inplace=True)

### Q23. ⭐ Interview Classic
Find the highest paid employee in each department. Do not use `groupby` — only use `sort_values()` and `drop_duplicates()`.

In [39]:
df.sort_values('salary', ascending=False).drop_duplicates(subset='department')

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18

### Q24. ⭐ Interview Classic
Rank employees by salary within their department — the highest salary in each department gets rank 1. Use `sort_values()` with multiple columns.

In [46]:
# df.sort_values(by=['department','salary'],ascending =[False,False])
df['salary_rank']= df.groupby('department')['salary'].rank(method='dense',ascending=False)

df

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,salary_rank
19,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,1.0
14,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,2.0
4,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,3.0
21,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,1.0
9,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,2.0
2,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,3.0
7,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,4.0
24,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,4.0
0,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,5.0
11,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,5.0
18,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,6.0
5,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,7.0
15,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,8.0
16,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,1.0
1,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,2.0
23,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,6.0
6,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,3.0
20,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,4.0
22,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,1.0
3,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,2.0
13,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,3.0
8,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,4.0
10,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,5.0
12,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,NaN
17,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,NaN

### Q25. Sort by `salary` descending and add a new column called `salary_rank` that numbers each row 1, 2, 3... after sorting.

In [52]:
df=df.sort_values(by='salary',ascending=False).reset_index(drop=True)
df['salary_rank']=df.index+1
df

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,salary_rank
0,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,1
1,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,2
2,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,3
3,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,4
4,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,5
5,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,6
6,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,7
7,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,8
8,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,9
9,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,10
10,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,11
11,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,12
12,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,13
13,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,14
14,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,15
15,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,16
16,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,17
17,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,18
18,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,19
19,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,20
20,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,21
21,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,22
22,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,23
23,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,24
24,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,25

### Q26. ⭐ Interview Classic
Get the top 3 employees by `projects_completed` from EACH department separately. (Think: filter each department, nlargest, combine results.)

In [54]:
top3 = (
    df.groupby('department', group_keys=False)
      .apply(lambda x: x.nlargest(3, 'projects_completed'))
)
top3

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,salary_rank
3,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,4
4,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,5
23,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,24
0,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,1
1,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,2
2,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,3
18,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,19
21,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,22
19,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,20
13,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,14
16,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,17
14,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,15

### Q27. ⭐ Interview Classic
Sort the DataFrame by `salary` but treat NaN salaries as if they were `0` during sorting — without actually filling them in the original data.

In [55]:
df.sort_values('salary', key=lambda x: x.fillna(0), ascending=False)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,salary_rank
0,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,1
1,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,2
2,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,3
3,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,4
4,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,5
5,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,6
6,108,Meera Joshi,31,Female,Finance,Pune,98000.0,7,4.4,2017,True,28,7
7,125,Aditi Sharma,30,Female,Engineering,Mumbai,97000.0,7,4.4,2017,False,24,8
8,101,Arjun Sharma,32,Male,Engineering,Bangalore,95000.0,8,4.5,2016,True,23,9
9,112,Lakshmi Pillai,30,Female,Finance,Bangalore,92000.0,7,4.3,2017,False,22,10
10,119,Kavya Menon,31,Female,Engineering,Kochi,91000.0,8,4.5,2016,False,25,11
11,106,Divya Iyer,29,Female,Engineering,Chennai,88000.0,6,4.6,2018,False,19,12
12,116,Ishaan Chopra,29,Male,Engineering,Chandigarh,84000.0,6,3.7,2018,False,16,13
13,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,14
14,102,Priya Nair,28,Female,Marketing,Mumbai,72000.0,5,4.2,2019,False,14,15
15,124,Manish Tiwari,28,Male,Finance,Lucknow,70000.0,5,3.8,2019,False,13,16
16,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,17
17,121,Nisha Agarwal,27,Female,Marketing,Delhi,63000.0,4,4.0,2020,False,12,18
18,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,19
19,104,Sneha Patel,26,Female,HR,Ahmedabad,55000.0,3,4.7,2021,False,8,20
20,114,Pooja Reddy,25,Female,HR,Hyderabad,53000.0,2,4.5,2022,False,6,21
21,109,Vivek Singh,27,Male,HR,Mumbai,51000.0,4,3.9,2020,False,10,22
22,111,Rahul Verma,24,Male,Marketing,Jaipur,45000.0,1,3.6,2023,False,4,23
23,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,24
24,118,Siddharth Roy,22,Male,HR,Mumbai,NaN,1,3.4,2023,False,3,25

### Q28. After sorting by `salary` descending, check if the index is still in its original order. Then reset it and verify.

In [56]:
df_sorted = df.sort_values('salary', ascending=False)

print(df_sorted.index)

df_sorted = df_sorted.reset_index(drop=True)

print(df_sorted.index)

RangeIndex(start=0, stop=25, step=1)
RangeIndex(start=0, stop=25, step=1)

### Q29. ⭐ Interview Classic
Find the second highest salary in the dataset without using `nlargest()` directly — use `sort_values()` and iloc.

In [66]:
df.sort_values(by='salary',ascending=False).iloc[1]

# df.nlargest(2,'salary').iloc[1]

employee_id                     115
name                  Arjun Nambiar
age                              43
gender                         Male
department                  Finance
city                          Kochi
salary                     145000.0
experience_years                 19
rating                          4.6
joining_year                   2005
is_manager                     True
projects_completed               50
salary_rank                       2
Name: 1, dtype: object

### Q30. ⭐ Interview Classic
Sort employees by `experience_years` descending and `salary` descending. Then assign a `rank` column (1 being the most experienced and highest paid). Display the top 10.

In [75]:
df= df.sort_values(by=['experience_years','salary'],ascending=[False,False]).reset_index(drop=True)
df['rank']=df.index+1
df.head(10)

,employee_id,name,age,gender,department,city,salary,experience_years,rating,joining_year,is_manager,projects_completed,salary_rank,rank
0,120,Tarun Bhatt,45,Male,Finance,Ahmedabad,155000.0,21,4.7,2003,True,55,1,1
1,115,Arjun Nambiar,43,Male,Finance,Kochi,145000.0,19,4.6,2005,True,50,2,2
2,105,Kiran Rao,40,Male,Finance,Bangalore,130000.0,16,4.1,2008,True,42,3,3
3,122,Deepak Jain,39,Male,Engineering,Bangalore,120000.0,15,4.3,2009,True,40,4,4
4,113,Nikhil Gupta,38,Male,Engineering,Delhi,NaN,14,4.0,2010,True,35,24,5
5,110,Ananya Das,36,Female,Engineering,Kolkata,115000.0,12,4.8,2012,True,38,5,6
6,103,Rohan Mehta,35,Male,Engineering,Delhi,110000.0,11,3.8,2013,True,31,6,7
7,117,Riya Bose,34,Female,Marketing,Kolkata,75000.0,10,4.2,2014,False,21,14,8
8,107,Aditya Kumar,33,Male,Marketing,Delhi,68000.0,9,3.5,2015,False,17,17,9
9,123,Swati Kulkarni,33,Female,HR,Pune,58000.0,9,4.6,2015,False,18,19,10

---
## ✅ Done with Sorting & Ordering!

| Method | Practiced in |
|--------|--------------|
| `df.sort_values()` | Q1–Q4, Q8, Q10–Q14, Q17, Q18, Q20–Q25, Q27–Q30 |
| `df.sort_index()` | Q7, Q15 |
| `df.nlargest()` | Q5, Q9, Q16, Q21, Q26 |
| `df.nsmallest()` | Q6, Q19 |
| Multi-column sort | Q11, Q12, Q13, Q20, Q24, Q30 |
| `inplace=True` | Q22 |

**Next up → GroupBy 🚀**